import fs from "fs";
import path from "path";

import yargs from "yargs";

// Get our args
const argv = yargs(process.argv).argv;
const { app, output } = argv;

const folderPath = "./locales/" + app;
const namefile = "translations.json";
const jsonI18n = {};

// Crowdin outputs one folder per locale (fr-FR, zh-CN, zh-TW, en...)
const locales = fs.readdirSync(folderPath).filter((entry) => {
  // Crowdin output file in folder, we want to treat only these ones
  return fs.lstatSync(path.join(folderPath, entry)).isDirectory();
});

const getLanguage = (locale) => locale.split(/[-_]/)[0].toLowerCase();

const localesPerLanguage = {};
locales.forEach((locale) => {
  const language = getLanguage(locale);
  localesPerLanguage[language] = (localesPerLanguage[language] ?? 0) + 1;
});

// The language alone (fr) is enough when only one locale of it is translated,
// the region is kept (zh-cn, zh-tw) when the locales would otherwise collide.
const getKey = (locale) =>
  localesPerLanguage[getLanguage(locale)] > 1
    ? locale.replace("_", "-").toLowerCase()
    : getLanguage(locale);

// Fetch the files in the locales folder
locales.forEach((locale) => {
  const language = getKey(locale);
  const languagePath = path.join(folderPath, path.sep, locale);

  jsonI18n[language] = {
    translation: {},
  };

  // Get the json file generated by crowdin
  const pathTranslateFile = path.join(languagePath, path.sep, namefile);

  if (!fs.existsSync(pathTranslateFile)) {
    throw new Error(`File ${pathTranslateFile} not found!`);
  }

  const json = JSON.parse(fs.readFileSync(pathTranslateFile, "utf8"));

  // Transform the json file to the format expected by i18next
  const jsonKeyMessage = {};
  Object.keys(json)
    .sort()
    .forEach((key) => {
      jsonKeyMessage[key] = json[key].message;
    });

  jsonI18n[language] = {
    translation: jsonKeyMessage,
  };
});

if (!Object.keys(jsonI18n).length) {
  throw new Error(`No translation to deploy`);
}

// Write the file to the output
fs.writeFileSync(output, JSON.stringify(jsonI18n), "utf8");

console.log(`${app} translations deployed!`);
