# Generated by Django 5.2.13 on 2026-09-17 11:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "slug",
                    models.CharField(max_length=64, unique=True, verbose_name="slug"),
                ),
                (
                    "livekit_room",
                    models.CharField(
                        help_text="Identifier of the Meet room, used as the LiveKit room name.",
                        max_length=64,
                        unique=True,
                        verbose_name="LiveKit room",
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(
                        blank=True,
                        help_text="Matrix room the meeting belongs to.",
                        max_length=255,
                        verbose_name="conversation",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="title"),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="starts on"
                    ),
                ),
                (
                    "planned_end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Past this time, the meeting closes once nobody is in it.",
                        null=True,
                        verbose_name="planned end",
                    ),
                ),
                ("agenda", models.TextField(blank=True, verbose_name="agenda")),
                (
                    "time_zone",
                    models.CharField(
                        default="UTC",
                        help_text="Of the organizer's browser: times in the archive use it.",
                        max_length=64,
                        verbose_name="time zone",
                    ),
                ),
                (
                    "last_occupied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last occupied on"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="closed on"
                    ),
                ),
                (
                    "auto_closed",
                    models.BooleanField(
                        default=False, verbose_name="closed automatically"
                    ),
                ),
                (
                    "transcript_document_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="transcript document",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "meeting",
                "verbose_name_plural": "meetings",
                "db_table": "hub_meeting",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("content", models.TextField(verbose_name="content")),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.meeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "meeting attachment",
                "verbose_name_plural": "meeting attachments",
                "db_table": "hub_meeting_attachment",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(max_length=128, verbose_name="message id"),
                ),
                (
                    "sender_identity",
                    models.CharField(max_length=255, verbose_name="sender identity"),
                ),
                (
                    "sender_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="sender name"
                    ),
                ),
                ("text", models.TextField(verbose_name="text")),
                (
                    "sent_at",
                    models.DateTimeField(
                        help_text="When the scribe received the message.",
                        verbose_name="sent on",
                    ),
                ),
                (
                    "from_assistant",
                    models.BooleanField(
                        default=False,
                        help_text="Written by Ariane, for the scribe to post in the call.",
                        verbose_name="from the assistant",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the scribe took an assistant message to post it.",
                        null=True,
                        verbose_name="delivered on",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="core.meeting",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="core.meetingchatmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "meeting chat message",
                "verbose_name_plural": "meeting chat messages",
                "db_table": "hub_meeting_chat_message",
                "ordering": ["sent_at", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("meeting", "message_id"),
                        name="unique_chat_message_per_meeting",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MeetingParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("identity", models.CharField(max_length=255, verbose_name="identity")),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="name"),
                ),
                ("first_seen_at", models.DateTimeField(verbose_name="first seen on")),
                ("last_seen_at", models.DateTimeField(verbose_name="last seen on")),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="core.meeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "meeting participant",
                "verbose_name_plural": "meeting participants",
                "db_table": "hub_meeting_participant",
                "ordering": ["first_seen_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("meeting", "identity"),
                        name="unique_participant_per_meeting",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MeetingTranscriptSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "segment_id",
                    models.CharField(max_length=128, verbose_name="segment id"),
                ),
                (
                    "speaker_identity",
                    models.CharField(max_length=255, verbose_name="speaker identity"),
                ),
                (
                    "speaker_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="speaker name"
                    ),
                ),
                ("text", models.TextField(verbose_name="text")),
                (
                    "spoken_at",
                    models.DateTimeField(
                        help_text="When the scribe received the sentence.",
                        verbose_name="spoken on",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_segments",
                        to="core.meeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "meeting transcript segment",
                "verbose_name_plural": "meeting transcript segments",
                "db_table": "hub_meeting_transcript_segment",
                "ordering": ["spoken_at", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("meeting", "segment_id"),
                        name="unique_segment_per_meeting",
                    )
                ],
            },
        ),
    ]
