# Generated by Django 5.2.13 on 2026-10-07 11:37

from django.db import migrations, models

OFFERED_LANGUAGES = ["en-us", "fr-fr"]


def clear_unoffered_languages(apps, schema_editor):
    """Reset the profile language of users who chose a language no longer offered."""
    User = apps.get_model("core", "User")
    User.objects.exclude(language__in=OFFERED_LANGUAGES).exclude(
        language__isnull=True
    ).update(language=None)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(clear_unoffered_languages, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("en-us", "English"), ("fr-fr", "Français")],
                default=None,
                help_text="The language in which the user wants to see the interface.",
                max_length=10,
                null=True,
                verbose_name="language",
            ),
        ),
    ]
