# Generated by Django 5.2.13 on 2026-05-26 13:26

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('kind', models.CharField(choices=[('SELF', 'self chat'), ('DIRECT', 'direct chat'), ('GROUP', 'group chat')])),
                ('name', models.CharField()),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'GROUP'), models.Q(('name', ''), _negated=True)), models.Q(models.Q(('kind', 'GROUP'), _negated=True), ('name', '')), _connector='OR'), name='check_only_groups_have_name')],
            },
        ),
    ]
