# Generated by Django 5.2.13 on 2026-09-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_meetings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="matrix_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="professional_role",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
