# Generated by Django 5.2.13 on 2026-05-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chat_service_id',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True),
        ),
    ]
