# Generated by Django 5.2.13 on 2026-05-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conversation_chat_service_id_alter_conversation_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='check_only_groups_have_name',
        ),
        migrations.AddField(
            model_name='conversation',
            name='chat_service_kind',
            field=models.CharField(choices=[('TCHAP', 'Tchap')], default='TCHAP'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('DIRECT', 'direct chat'), ('GROUP', 'group chat')], default='DIRECT'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(models.F('chat_service_kind'), models.F('chat_service_id'), name='uniq_chat_service_kind_and_id'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'GROUP'), models.Q(('name', ''), _negated=True)), models.Q(('kind', 'DIRECT'), ('name', '')), _connector='OR'), name='check_only_groups_have_name'),
        ),
    ]
